name: Rebuild Images

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  develop-with-pony:
    name: Develop with Pony
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and Push
        run: bash develop-with-pony/build-and-push.sh

  dependent-on-develop-with-pony:
    needs:
      - develop-with-pony

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env-name:
          - develop-credo
          - develop-lori
          - develop-postgres

    name: Develop ${{ matrix.env-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and Push
        run: bash ${{ matrix.env-name }}/build-and-push.sh

  prune-untagged-images:
    needs:
      - develop-with-pony
      - dependent-on-develop-with-pony

    name: Prune untagged images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package-name:
          - dev-environment-develop-with-pony
          - dev-environment-develop-credo
          - dev-environment-develop-lori
          - dev-environment-develop-postgres

    steps:
      - name: Prune
        # v5.0.0
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
