name: Daily Image Builds

on:
  schedule:
    - cron: '0 7 * * *'

permissions:
  packages: write

jobs:
  develop-with-pony:
    name: Develop with Pony
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and Push
        run: bash develop-with-pony/build-and-push.sh

  develop-credo:
    name: Develop credo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and Push
        run: bash develop-credo/build-and-push.sh

  prune-untagged-images:
    needs:
      - develop-with-pony
      - develop-credo

    name: Prune untagged images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package-name: ['develop-with-pony', 'develop-credo']

    steps:
      - name: Prune
        # v4.1.1
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'

