name: Validate Images

on: pull_request

concurrency:
  group: validate-images-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  validate-images:
    name: Validate ${{ matrix.image-type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image-type: 'develop-with-pony'
            display-name: 'Develop with Pony'
          - image-type: 'develop-credo'
            display-name: 'Develop credo'
          - image-type: 'develop-lori'
            display-name: 'Develop lori'
          - image-type: 'develop-postgres'
            display-name: 'Develop postgres'

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: "docker build --pull --file=${{ matrix.image-type }}/Dockerfile ."
